name: Build and Publish to PyPI

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Lint with ruff
      run: |
        uv run --frozen ruff check .
        uv run --frozen ruff format --check .
    
    - name: Type check with mypy
      run: |
        uv run --frozen mypy src
    
    - name: Run tests
      run: |
        uv run --frozen pytest tests/ -v --cov=uv_outdated --cov-report=xml
    
  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: '3.12'
    
    - name: Build wheel
      run: uv build
    
    - name: Publish package
      run: uv publish
